# Generated by Django 6.0.2 on 2026-02-11 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MAINTENANCE', 'Maintenance')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fleet.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveBooking',
            fields=[
            ],
            options={
                'verbose_name': 'Active Booking',
                'verbose_name_plural': 'Active Bookings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.booking',),
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Booking',
                'verbose_name_plural': 'Archived Bookings (Completed/Cancelled)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.booking',),
        ),
    ]
