# Generated by Django 6.0.2 on 2026-02-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=201)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many of this car do you have?')),
                ('cleaning_time', models.PositiveIntegerField(default=1, help_text='Hours needed for cleaning between trips.')),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], max_length=10)),
                ('seats', models.IntegerField(default=5)),
                ('doors', models.IntegerField(default=4)),
                ('fuel_type', models.CharField(default='Petrol', max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='price for 24 hours', max_digits=10)),
                ('twelve_hour_rate', models.DecimalField(decimal_places=2, help_text='price for 12 hours', max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('image', models.ImageField(upload_to='cars/')),
                ('is_featured', models.BooleanField(default=False)),
                ('features', models.TextField(blank=True, help_text='comma separated (e.g. GPS, Bluetooth, sunroof)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='fleet.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
